### ISSUE TITLE
MIT license violations

### ISSUE THREAD

**Issue by iddm** [bk-rs/serde-ext#1]
Hi bk-rs and @vkill. By accident, I have noticed this repository recently and some other repositories. I noticed that [a commit of two months ago](https://github.com/bk-rs/serde-ext/commit/328a746a7c35025f225b91a99d661bf4c143aef3) copies a substantial part of my code which has been licensed under the MIT license. The license is very permissive but still - a license, so has requirements. Those requirements are pretty simple:

> The MIT License requires two things in your copy and/or modification of the code: The original copyright notice. A copy of the license itself.

I failed to notice such things in your copy, so I kindly ask you to add them.

**Comment by vkill** [comment]
Hi @vityafx 

I'm very sorry, I just copied the code directly for my convenience, and the copyright has been added. https://github.com/bk-rs/serde-ext/commit/0918f05129210310ad55f3807238ac1ff6b855f4

**Comment by iddm** [comment]
Hi @vkill, and thanks for that.
Unfortunately, this isn't all. You should also copy the [LICENSE file from my repository](https://github.com/vityafx/serde-aux/blob/master/LICENSE) to [yours](https://github.com/bk-rs/serde-ext/blob/main/serde-aux-ext/LICENSE-MIT) where the `serde-aux-ext` is. Sublicensing with apache 2 is acceptable in this case, and you can leave it.

**Comment by vkill** [comment]
Hi @vityafx

The LICENSE file has been copied. https://github.com/bk-rs/serde-ext/commit/009a306cbe146ac6112435ea896b638bf9791dd8

**Comment by iddm** [comment]
Thank you, @vkill. Now it is all according to the license.
Have a great day! If you find that something may be improved in the serde-aux library, feel free to create an issue there and raise a discussion.
